import 'package:cracte/src/common/common.dart';

const appName = 'cracte';

const themeNameKey = 'theme';

final List<Category> categories = [
  Category(id: '1', name: 'Breakfast'),
  Category(id: '2', name: 'Lunch'),
  Category(id: '3', name: 'Dinner'),
  Category(id: '4', name: 'Desserts'),
];

final List<Recipe> recipes = [
  // Breakfast
  Recipe(
    id: 'b1',
    title: 'Pancakes',
    image: 'https://images.pexels.com/photos/718739/pexels-photo-718739.jpeg',
    description: 'Fluffy pancakes served with syrup.',
    ingredients: ['Flour', 'Eggs', 'Milk', 'Baking powder', 'Sugar'],
    steps: [
      'Mix ingredients to form batter.',
      'Cook on a hot pan until golden.',
    ],
    authorId: 'u1',
    authorName: 'Emily Clark',
    authorImage: 'https://randomuser.me/api/portraits/women/1.jpg',
    duration: 15,
    category: Category(id: '1', name: 'Breakfast'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'b2',
    title: 'Avocado Toast',
    image: 'https://images.pexels.com/photos/1321942/pexels-photo-1321942.jpeg',
    description: 'Crispy toast topped with mashed avocado.',
    ingredients: ['Bread', 'Avocado', 'Salt', 'Lemon juice'],
    steps: ['Toast bread slices.', 'Top with mashed avocado and seasoning.'],
    authorId: 'u2',
    authorName: 'David Smith',
    authorImage: 'https://randomuser.me/api/portraits/men/2.jpg',
    duration: 10,
    category: Category(id: '1', name: 'Breakfast'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'b3',
    title: 'Omelette',
    image: 'https://images.pexels.com/photos/6294359/pexels-photo-6294359.jpeg',
    description: 'Quick and easy egg omelette.',
    ingredients: ['Eggs', 'Onion', 'Pepper', 'Cheese'],
    steps: ['Whisk eggs with vegetables.', 'Cook in pan until set.'],
    authorId: 'u3',
    authorName: 'Anna White',
    authorImage: 'https://randomuser.me/api/portraits/women/3.jpg',
    duration: 8,
    category: Category(id: '1', name: 'Breakfast'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'b4',
    title: 'Fruit Salad',
    image:
        'https://images.pexels.com/photos/11690680/pexels-photo-11690680.jpeg',
    description: 'Refreshing salad with seasonal fruits.',
    ingredients: ['Apple', 'Banana', 'Grapes', 'Orange'],
    steps: ['Chop all fruits.', 'Toss together and chill before serving.'],
    authorId: 'u4',
    authorName: 'Chris Jordan',
    authorImage: 'https://randomuser.me/api/portraits/men/4.jpg',
    duration: 5,
    category: Category(id: '1', name: 'Breakfast'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'b5',
    title: 'Smoothie Bowl',
    image: 'https://images.pexels.com/photos/7936988/pexels-photo-7936988.jpeg',
    description: 'Thick smoothie served in a bowl.',
    ingredients: ['Banana', 'Berries', 'Yogurt', 'Granola'],
    steps: ['Blend fruits and yogurt.', 'Pour into bowl and top with granola.'],
    authorId: 'u5',
    authorName: 'Sophia Lee',
    authorImage: 'https://randomuser.me/api/portraits/women/5.jpg',
    duration: 7,
    category: Category(id: '1', name: 'Breakfast'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // Lunch
  Recipe(
    id: 'l1',
    title: 'Grilled Cheese Sandwich',
    image:
        'https://images.pexels.com/photos/30700608/pexels-photo-30700608.jpeg',
    description: 'Golden grilled cheese sandwich.',
    ingredients: ['Bread', 'Cheese', 'Butter'],
    steps: [
      'Place cheese between bread slices.',
      'Grill with butter until golden.',
    ],
    authorId: 'u1',
    authorName: 'Emily Clark',
    authorImage: 'https://randomuser.me/api/portraits/women/1.jpg',
    duration: 10,
    category: Category(id: '2', name: 'Lunch'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'l2',
    title: 'Caesar Salad',
    image:
        'https://images.pexels.com/photos/28933154/pexels-photo-28933154.jpeg',
    description: 'Classic salad with Caesar dressing.',
    ingredients: ['Lettuce', 'Croutons', 'Parmesan', 'Dressing'],
    steps: ['Toss lettuce with dressing.', 'Add croutons and cheese on top.'],
    authorId: 'u2',
    authorName: 'David Smith',
    authorImage: 'https://randomuser.me/api/portraits/men/2.jpg',
    duration: 12,
    category: Category(id: '2', name: 'Lunch'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'l3',
    title: 'Spaghetti Bolognese',
    image: 'https://images.pexels.com/photos/6287493/pexels-photo-6287493.jpeg',
    description: 'Spaghetti with meat sauce.',
    ingredients: ['Spaghetti', 'Ground beef', 'Tomato sauce'],
    steps: [
      'Cook pasta and meat sauce separately.',
      'Combine and simmer briefly.',
    ],
    authorId: 'u3',
    authorName: 'Anna White',
    authorImage: 'https://randomuser.me/api/portraits/women/3.jpg',
    duration: 20,
    category: Category(id: '2', name: 'Lunch'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'l4',
    title: 'Tuna Wrap',
    image: 'https://images.pexels.com/photos/9624298/pexels-photo-9624298.jpeg',
    description: 'Quick tuna wrap for lunch.',
    ingredients: ['Tortilla', 'Tuna', 'Mayo', 'Lettuce'],
    steps: ['Mix tuna and mayo.', 'Wrap with lettuce in tortilla.'],
    authorId: 'u4',
    authorName: 'Chris Jordan',
    authorImage: 'https://randomuser.me/api/portraits/men/4.jpg',
    duration: 6,
    category: Category(id: '2', name: 'Lunch'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'l5',
    title: 'Chicken Quesadilla',
    image: 'https://images.pexels.com/photos/5848702/pexels-photo-5848702.jpeg',
    description: 'Cheesy quesadilla with grilled chicken.',
    ingredients: ['Tortilla', 'Chicken', 'Cheese', 'Spices'],
    steps: [
      'Fill tortilla with cheese and chicken.',
      'Fold and grill until crispy.',
    ],
    authorId: 'u5',
    authorName: 'Sophia Lee',
    authorImage: 'https://randomuser.me/api/portraits/women/5.jpg',
    duration: 15,
    category: Category(id: '2', name: 'Lunch'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  // Dinner

  Recipe(
    id: 'd1',
    title: 'Spaghetti Bolognese',
    image:
        'https://images.pexels.com/photos/29707922/pexels-photo-29707922.jpeg',
    description: 'Classic Italian pasta dish with a rich meat sauce.',
    ingredients: [
      'Spaghetti',
      'Ground beef',
      'Tomato sauce',
      'Onion',
      'Garlic',
    ],
    steps: ['Cook pasta', 'Make meat sauce', 'Combine and serve'],
    authorId: 'u1',
    authorName: 'Anna Lee',
    authorImage: 'https://randomuser.me/api/portraits/women/1.jpg',
    duration: 40,
    category: Category(id: '3', name: 'Dinner'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'd2',
    title: 'Grilled Salmon',
    image:
        'https://images.pexels.com/photos/28321266/pexels-photo-28321266.jpeg',
    description: 'Perfectly grilled salmon with lemon butter.',
    ingredients: ['Salmon fillets', 'Lemon', 'Butter', 'Garlic', 'Parsley'],
    steps: ['Marinate salmon', 'Grill until flaky', 'Drizzle lemon butter'],
    authorId: 'u2',
    authorName: 'John Smith',
    authorImage: 'https://randomuser.me/api/portraits/men/2.jpg',
    duration: 30,
    category: Category(id: '3', name: 'Dinner'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'd3',
    title: 'Beef Stir Fry',
    image:
        'https://images.pexels.com/photos/31673756/pexels-photo-31673756.jpeg',
    description: 'Quick stir-fried beef and vegetables in soy sauce.',
    ingredients: [
      'Beef strips',
      'Bell peppers',
      'Soy sauce',
      'Garlic',
      'Onions',
    ],
    steps: ['Sauté beef', 'Add vegetables', 'Stir fry with sauce'],
    authorId: 'u3',
    authorName: 'Emily Carter',
    authorImage: 'https://randomuser.me/api/portraits/women/3.jpg',
    duration: 20,
    category: Category(id: '3', name: 'Dinner'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'd4',
    title: 'Vegetable Curry',
    image: 'https://images.pexels.com/photos/8289068/pexels-photo-8289068.jpeg',
    description: 'A hearty vegetable curry simmered in coconut milk.',
    ingredients: [
      'Potatoes',
      'Carrots',
      'Coconut milk',
      'Curry paste',
      'Spinach',
    ],
    steps: ['Cook veggies', 'Add curry paste', 'Simmer in coconut milk'],
    authorId: 'u4',
    authorName: 'Chris Jordan',
    authorImage: 'https://randomuser.me/api/portraits/men/4.jpg',
    duration: 35,
    category: Category(id: '3', name: 'Dinner'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'd5',
    title: 'BBQ Chicken Pizza',
    image:
        'https://images.pexels.com/photos/29839587/pexels-photo-29839587.jpeg',
    description: 'Homemade pizza topped with BBQ chicken and red onions.',
    ingredients: ['Pizza dough', 'BBQ sauce', 'Chicken', 'Onion', 'Mozzarella'],
    steps: ['Cook chicken', 'Assemble pizza', 'Bake until crispy'],
    authorId: 'u5',
    authorName: 'Sophia Lee',
    authorImage: 'https://randomuser.me/api/portraits/women/5.jpg',
    duration: 30,
    category: Category(id: '3', name: 'Dinner'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),

  Recipe(
    id: 'ds1',
    title: 'Chocolate Brownies',
    image:
        'https://images.pexels.com/photos/30353750/pexels-photo-30353750.jpeg',
    description: 'Rich and fudgy chocolate brownies with a crackly top.',
    ingredients: ['Chocolate', 'Flour', 'Sugar', 'Butter', 'Eggs'],
    steps: ['Melt chocolate', 'Mix all ingredients', 'Bake until set'],
    authorId: 'u1',
    authorName: 'Anna Lee',
    authorImage: 'https://randomuser.me/api/portraits/women/1.jpg',
    duration: 35,
    category: Category(id: '4', name: 'Dessert'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'ds2',
    title: 'Strawberry Cheesecake',
    image: 'https://images.pexels.com/photos/6133325/pexels-photo-6133325.jpeg',
    description: 'Creamy cheesecake topped with fresh strawberries.',
    ingredients: ['Cream cheese', 'Sugar', 'Graham crackers', 'Strawberries'],
    steps: ['Prepare crust', 'Mix filling', 'Chill and top with strawberries'],
    authorId: 'u2',
    authorName: 'John Smith',
    authorImage: 'https://randomuser.me/api/portraits/men/2.jpg',
    duration: 60,
    category: Category(id: '4', name: 'Dessert'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'ds3',
    title: 'Lemon Tart',
    image:
        'https://images.pexels.com/photos/30391249/pexels-photo-30391249.jpeg',
    description: 'Tangy lemon curd in a buttery tart shell.',
    ingredients: ['Lemon', 'Sugar', 'Butter', 'Eggs', 'Flour'],
    steps: ['Make tart shell', 'Cook lemon curd', 'Bake together'],
    authorId: 'u3',
    authorName: 'Emily Carter',
    authorImage: 'https://randomuser.me/api/portraits/women/3.jpg',
    duration: 50,
    category: Category(id: '4', name: 'Dessert'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'ds4',
    title: 'Tiramisu',
    image: 'https://images.pexels.com/photos/6213724/pexels-photo-6213724.jpeg',
    description: 'Classic Italian dessert with coffee-soaked ladyfingers.',
    ingredients: [
      'Mascarpone',
      'Coffee',
      'Ladyfingers',
      'Cocoa powder',
      'Sugar',
    ],
    steps: ['Layer ingredients', 'Chill overnight', 'Dust with cocoa'],
    authorId: 'u4',
    authorName: 'Chris Jordan',
    authorImage: 'https://randomuser.me/api/portraits/men/4.jpg',
    duration: 45,
    category: Category(id: '4', name: 'Dessert'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
  Recipe(
    id: 'ds5',
    title: 'Apple Pie',
    image: 'https://images.pexels.com/photos/5483815/pexels-photo-5483815.jpeg',
    description: 'Warm apple pie with a flaky crust and cinnamon spice.',
    ingredients: ['Apples', 'Cinnamon', 'Sugar', 'Pie crust'],
    steps: ['Prepare filling', 'Make crust', 'Bake till golden'],
    authorId: 'u5',
    authorName: 'Sophia Lee',
    authorImage: 'https://randomuser.me/api/portraits/women/5.jpg',
    duration: 60,
    category: Category(id: '4', name: 'Dessert'),
    createdAt: DateTime.now(),
    updatedAt: DateTime.now(),
  ),
];
